# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  [![Welcome Banner](https://zenodo.org/api/iiif/record:3695300:BannerWelcome.jpg/full/!750,750/0/default.jpg)](https://zenodo.org/record/3695300)

  ğŸ‰ Welcome to _The Turing Way_! ğŸ‰
  We're really excited to have your input into the project! ğŸ’–

  <br>If you haven't done so already, please make sure you check out our [Contributing Guidelines](https://github.com/the-turing-way/the-turing-way/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/the-turing-way/the-turing-way/blob/main/CODE_OF_CONDUCT.md).
  If you need to connect more synchronously with members of _The Turing Way_ community, please feel free to chat with us in our [Slack workspace](https://join.slack.com/t/theturingway/shared_invite/zt-fn608gvb-h_ZSpoA29cCdUwR~TIqpBw), or you can join our [Collaboration Cafe](https://the-turing-way.netlify.app/community-handbook/coworking/coworking-collabcafe.html) for mentored contribution or co-working.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  [![Thank You Banner](https://zenodo.org/api/iiif/record:3695300:BannerThanks.jpg/full/!750,750/0/default.jpg)](https://zenodo.org/record/3695300)

  ğŸ’– Thanks for opening this pull request! ğŸ’–
  _The Turing Way_ community really appreciates your time and effort to contribute to the project.
  Please make sure you have read our [Contributing Guidelines](https://github.com/the-turing-way/the-turing-way/blob/main/CONTRIBUTING.md) and filled in our pull request template to the best of your ability.

  If you are submitting a new chapter, here are some things that will help get your pull request across the finish line! ğŸ

  - Check you have removed all _lorem ipsums_ from the chapter template (if you used it)

  - Check for any abbreviations or latin phrases (such as "e.g." or "i.e.") in your writing. See our [style guide](https://github.com/the-turing-way/the-turing-way/blob/main/CONTRIBUTING.md#writing-style) for more information on this topic.

  - Make sure you have added your new chapter to the [Table of Contents](https://github.com/the-turing-way/the-turing-way/blob/main/book/website/_toc.yml)

  <br>We have Continuous Integration tests that check the writing style and will help you track down any slip-ups â™» 
  The Netlify bot will also comment with a preview of the book with your additions so you can see how it will look once it's merged! ğŸ‰

  <br>We get a lot of pull requests on this repo, so please be patient and we will get back to you as soon as we can.
  If we don't acknowledge this pull request after 7 days, feel free to chat to us about it in our [Slack workspace](https://join.slack.com/t/theturingway/shared_invite/zt-fn608gvb-h_ZSpoA29cCdUwR~TIqpBw).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  [![Congratulations Banner](https://zenodo.org/api/iiif/record:3695300:BannerCongratulations.jpg/full/!750,750/0/default.jpg)](https://zenodo.org/record/3695300)

  Congrats on merging your first pull request! ğŸ‰
  We here at _The Turing Way_ are proud of you! ğŸ’–
  Thank you so much for your contribution ğŸ
