# refer to https://docs.travis-ci.com/user/languages/minimal-and-generic/#generic
# for the rationale behind choosing the generic lang
language: generic
dist: xenial # ubuntu 16.04
matrix:
  include:
  - os: linux
    env: PYTHON=3.6

cache: bundler 

before_install: # get a reasonably new version of python3 and pip 
    - sudo apt-get install python3-pip
    - sudo -H pip3 install --upgrade pip
    - sudo apt-get install python3-setuptools

install:
    - pip3 install --user -r ./book/website/requirements.txt # install things for the book
    - pip3 install --user -U attrs pytest # the installed versions in Travis are too old!

script: 
    - bash ./scripts/test-file-size.sh # test that we haven't accidentally included any big files
    - python3 ./scripts/lorem-ipsums.py # check for rogue "lorem ipsum"s
    - python3 ./scripts/no-bad-latin.py # checks for examples of latin abbreviations like e.g., i.e. and e.t.c.
    # Below here, "scripts" directory refers to the one in book/website:
    - cd ./book/website
    - make install # install jekyll etc. for building website
    - bash ./scripts/html-proof.sh # check dead links etc.
