contact_links:
  - name: "\U0001F525 Suggest a Fireside Chat"
    url: https://github.com/the-turing-way/fireside-chats/issues/new?template=12_fireside_chat_checklist.md
    about: Resources and checklist for giving a talk about the Turing Way
  - name: "\U0001F4E3 Give a talk"
    url: https://github.com/the-turing-way/conferences/issues/new?assignees=&labels=talks-and-workshops%2Cnewsletter&projects=&template=give_a_talk.yml&title=%5BTALK%5D+%3Ctitle%3E
    about: Resources and checklist for giving a talk about the Turing Way
  - name: "\u2615 Collaboration cafe"
    url: https://book.the-turing-way.org/community-handbook/community-calls/community-calls-collabcafe/
    about: Sign up for mentored sprints and co-working sessions with Turing Way community members
  - name: "\U0001F5E3 All other questions and general chat"
    url: https://slack.the-turing-way.org
    about: Chat with the Turing Way community on Slack
