# Give your test a name!
name: Check for Lorem Ipsums

# Decide when to run the tests
#
# This configuration sets the test to run on pushes to main
# and on pull requests that are opened to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "book/**"

# Set up the Continuous Integration job
jobs:
  lorem-ipsums:
    if: (github.event.pull_request) && !contains(github.head_ref, 'all-contributors')
    # Run on the latest Ubuntu distribution
    runs-on: ubuntu-latest
    # This section collects together the steps involved in running the test
    steps:
      # Checkout the repository. Relies on another GH-Action.
      - uses: actions/checkout@v3
      # Set up the Python version. Relies on another GH-Action.
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      # Install Python dependencies
      - name: Install dependencies
        working-directory: ./tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      # Run a Python script
      - name: Run Python script to check for rogue "Lorem ipsums" - Pull Request
        working-directory: ./tests
        if: github.event.pull_request
        run: |
          python lorem-ipsums.py --pull-request ${{ github.event.pull_request.number }}

      - name: Run Python script to check for rogue "Lorem ipsums" - Main branch
        working-directory: ./tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          python lorem-ipsums.py
